document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						<div class="PrincipalInvestigatorSingle">');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						<ol class="inlineblock">');
document.write('							<li class="PrincipalInvestigatorFig">');
document.write('								<img src="' + img + '" width="100%" alt="保存禁止" border="0">');
document.write('							</li>');
document.write('							<li class="PIinfo">');
document.write('								<span style="font-size:130%;font-family:Helvetica-Bold">');
document.write('									' + name + ' ');
document.write('								</span>');
document.write('								<span style="font-size:110%;font-family:Helvetica">');
document.write('									' + age + '<br>');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('									&ensp;&ensp;&ensp;&ensp;&ensp;' + position + '<br>');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('								<a href="' + urlSOAR + '" class="hoverline" target="_blank">');
document.write('									' + contactinfo + '<br>');
document.write('								</a>');
document.write('								</span>');
document.write('							</li><br>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategoryOne + '<br>');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('									' + HighSchool + '<br>');
document.write('									' + Undergraduate + '<br>');
document.write('									' + MasterCourse + '<br>');
document.write('									' + DoctorCourse + '<br>');
document.write('									' + PhD + ' ');
document.write('								</span>');
document.write('							</li>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategoryTwo + '<br>');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('									' + AssistantProfwithoutTenure + '<br>');
document.write('									' + AssistantProf + '<br>');
document.write('									' + AssistantProf_kaiso + '<br>');
document.write('									' + AssociateProf + '<br>');
document.write('									' + ResearchCenter + '<br>');
document.write('									' + FullProf + '<br>');
document.write('								</span>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategoryThree + '<br>');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('									' + Award_MEXT_2023 + '<br>');
document.write('									' + Award_DandS_2021 + '<br>');
document.write('									' + Award_DandS_2017 + '<br>');
document.write('									' + Award_JASCOME + '<br>');
document.write('									' + Award_NU + '<br>');
document.write('								</span>');
document.write('							</li>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategoryFour + ' ');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('								<a href="' + urlFour + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value=list>');
document.write('								</a>');
document.write('								</span>');
document.write('							</li>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategoryFive + ' ');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('								<a href="' + urlFive + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value=list>');
document.write('								</a>');
document.write('								</span>');
document.write('							</li>');
document.write('							<li class="Category">');
document.write('								<span style="font-size:120%;font-family:Helvetica-bold">');
document.write('									' + CategorySix + ' ');
document.write('								</span>');
document.write('								<span style="font-size:100%;font-family:Helvetica">');
document.write('								<a href="' + urlSix + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value=list>');
document.write('								</a>');
document.write('								</span>');
document.write('							</li>');
document.write('						</ol>');
document.write('	');
document.write('						<div class="PIPower">');
document.write('						<ol class="inlineblock">');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlGoogleSchalor + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + GoogleSchalor + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlScopus + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + Scopus + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlWoS + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + WoS + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlRG + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + RG + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlKAKEN + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + KAKEN + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlORCiD + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + ORCiD + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlKUDOS + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + KUDOS + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlRM + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + RM + '">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="PILink">');
document.write('								<a href="' + urlSOAR + '" class="hoverline" target="_blank">');
document.write('									<input type="button" value="' + SOAR + '">');
document.write('								</a>');
document.write('							</li>');
document.write('						</ol>');
document.write('						</div><!--PIPower-->');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						</div><!--PrincipalInvestigatorSingle-->');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');