document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						<div class="PaperSingle">');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						<ol class="inlineblock">');
document.write('							<li class="paperfig">');
document.write('								<a href="' + url + '" target="_blank">');
document.write('									<img src="' + img + '" height="100%" width="100%" alt="保存禁止" border="0">');
document.write('								</a>');
document.write('							</li>');
document.write('							<li class="paperinfo">');
document.write('								<span style="font-size:108%;font-family:Helvetica-Bold">' + title + '</span>');
document.write('								<span style="font-size:100%;font-family:Times">' + language + '</span><br>');
document.write('								<span style="font-size:100%;font-family:Times">' + author + '</span><br>');
document.write('								<a href="' + url + '" target="_blank">');
document.write('									<span style="font-size:100%;font-family:Times;font-style:Italic">' + journal + '</span> &nbsp;');
document.write('									<span style="font-size:100%;font-family:Times;font-style:Roman">' + volnop + '</span>.');
document.write('								</a>');
document.write('							</li>');
document.write('						</ol>');
document.write('						');
document.write('						<div class="JournalPower">');
document.write('						<ol class="inlineblock">');
document.write('							<li class="paperIF">');
document.write('							Impact factor<br> ' + yearif + ' : <font face="Helvetica-Bold">' + impactfactor + '</font>');
document.write('						</li>');
document.write('						<li class="paperh5index">');
document.write('							<a href="' + urlh5 + '" target="_blank">');
document.write('								Google Scholar h5-index : <font face="Helvetica-Bold" color="black">' + h5index + '</font> (' + yearh5 + ')<br>');
document.write('								(ranked <font face="Helvetica-Bold" color="black">' + rankh5 + '</font> in ' + categoryh5 + ')</a>');
document.write('						</li></ol>');
document.write('						</div><!--JournalPower-->');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('						</div><!--PaperSingle-->');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');