document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('<div class="studentSingle">');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('	<div class="studenthighlight">');
document.write('		<div class="studentfig">');
document.write('			<a href="' + url + ' " target="_blank">');
document.write('				<img src="' + img + '" ' + option + '="' + opttype + '" width="100%" height="100%" alt="loading..." border="0">');
document.write('			</a>');
document.write('		</div>');
document.write('		<div class="studentinfo">');
document.write('			<a href="' + urltalk + '" target="_blank">');
document.write('				<span style="font-size:80%;font-family:Helvetica;font-style:Bold;color:#000000;">' + info + '</span>&nbsp;');
document.write('			</a>');
document.write('			<br>');
document.write('			<span style="font-size:80%;font-family:Helvetica-Bold;line-height:20%;">' + title +'</span>, ');
document.write('			<span style="font-size:80%;font-family:Times;">' + language + '</span>');
document.write('			<a href="' + url + '" target="_blank">');
document.write('				<span style="font-size:80%;font-family:Times;font-style:Italic;">' + journal + '</span>&nbsp;');
document.write('				<span style="font-size:80%;font-family:Times;font-style:Roman;">' + volnop + '</span>.');
document.write('			</a>');
document.write('		</div>');
document.write('	</div>');
document.write('						');

document.write('	<div class="studentConferenceInfo">');
document.write('		<div class="studenttalkdate">');
document.write('			' + date + ' <font face="Helvetica-Bold">' + year + '</font>');
document.write('		</div>');
document.write('		<div class="studenttalkvenues">');
document.write('			<a href="' + urlvenues + '">');
document.write('				<!--Venues : <font face="Helvetica-Bold" color="black">' + venues + '</font>');
document.write('				at <font face="Helvetica-Bold" color="black">' + city + '</font> (' + country + ')-->');
document.write('				<font face="Helvetica-Bold" color="black">' + venues + '</font>');
document.write('				(<font face="Helvetica-Bold" color="black">' + city + '</font>' + country + ')');
document.write('			</a>');
document.write('		</div>');
document.write('	</div><!--studentConferenceInfo-->');

document.write('<!--------------------------------------------------------------------------------------------------------------------------->');
document.write('					</div><!--studentSingle-->');
document.write('<!--------------------------------------------------------------------------------------------------------------------------->');